# Generated by Django 5.1.2 on 2024-11-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_user_date_joined_user_google_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='street',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
