# Generated by Django 5.1.2 on 2024-11-19 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_street'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.channel'),
        ),
    ]
