# Generated by Django 5.1.2 on 2024-11-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_category_remove_video_channel_remove_video_dislikes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
