# Generated by Django 5.1.2 on 2024-11-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_remove_content_owner_content_uploader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='views',
        ),
        migrations.AddField(
            model_name='content',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
