# Generated by Django 5.1.2 on 2024-11-10 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_remove_content_views_content_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortvideo',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.content'),
        ),
    ]
