# Generated by Django 5.1.2 on 2024-11-10 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_shortvideo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortvideo',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.category'),
        ),
    ]
