# Generated by Django 5.1.2 on 2024-11-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='send_notification_email',
            field=models.BooleanField(default=True),
        ),
    ]
