# Generated by Django 5.1.2 on 2024-11-08 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notificationsettings_send_notification_email'),
        ('videos', '0005_alter_content_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='video',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.content'),
        ),
    ]
