# Generated by Django 5.1.2 on 2024-11-08 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notifications_video'),
        ('videos', '0005_alter_content_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.content'),
        ),
    ]
