# Generated by Django 5.1.2 on 2024-11-08 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notifications_video'),
        ('videos', '0006_remove_content_owner_content_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.content'),
        ),
    ]
